drop table country if exists;
drop table match if exists;
drop table match_team if exists;
drop table point if exists;
drop table sport if exists;
drop table team if exists;
drop table tournament if exists;
drop table town if exists;

create table country (
	id bigint generated by default as identity, 
	code int(3) NOT NULL,
	alpha2 varchar(2) NOT NULL,
	alpha3 varchar(3) NOT NULL,
	name varchar(45) NOT NULL,
	primary key (id)
);
	
create table match (
	id bigint generated by default as identity, 
	date timestamp, 
	tournament_id bigint not null, 
	primary key (id)
);

create table match_team (
	match_id bigint not null, 
	team_id bigint not null
);

create table point (
	id bigint generated by default as identity, 
	date_time timestamp, 
	type_point varchar(255), 
	match_id bigint not null, 
	team_id bigint not null, 
	primary key (id)
);

create table sport (
	id bigint generated by default as identity, 
	name varchar(255), 
	primary key (id)
);

create table team (
	id bigint generated by default as identity, 
	age varchar(255), 
	name varchar(255), 
	town_id bigint not null, 
	primary key (id)
);

create table tournament (
	id bigint generated by default as identity, 
	name varchar(255), 
	tournament_date timestamp, 
	sport_id bigint not null, 
	town_id bigint not null, 
	primary key (id)
);

create table town (
	id bigint generated by default as identity, 
	name varchar(255), 
	postal_code varchar(255), 
	country_id bigint not null, 
	primary key (id)
);

alter table match
	add constraint FK_match_tournament
	foreign key (tournament_id) 
	references tournament;
	
alter table match_team 
	add constraint FK_match_team_team 
	foreign key (team_id) 
	references team;

alter table match_team 
	add constraint FK_match_team_match 
	foreign key (match_id) 
	references match;

alter table point 
	add constraint FK_point_match
	foreign key (match_id) 
	references match;

alter table point 
	add constraint FK_point_team
	foreign key (team_id) 
	references team;

alter table team 
	add constraint FK_team_town
	foreign key (town_id) 
	references town;

alter table tournament 
	add constraint FK_tournament_sport
	foreign key (sport_id) 
	references sport;

alter table tournament 
	add constraint FK_tournament_town
	foreign key (town_id) 
	references town;

alter table town 
	add constraint FK_town_country
	foreign key (country_id) 
	references country;
